# Generated by Django 5.0.4 on 2024-05-30 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0002_contactus_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'Contact us'},
        ),
    ]
