# Generated by Django 5.0.4 on 2024-05-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='media')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(max_length=10000)),
                ('brand', models.CharField(max_length=255)),
                ('modelname', models.CharField(max_length=255)),
                ('specs', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Bikes',
            },
        ),
    ]
