# Generated by Django 5.0.4 on 2024-05-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tyre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='media')),
                ('description', models.TextField(max_length=10000)),
                ('width', models.CharField(max_length=10)),
                ('colour', models.CharField(max_length=20)),
                ('brand_name', models.CharField(max_length=20)),
                ('model_name', models.CharField(max_length=30)),
                ('weight_grams', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Wheel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='media')),
                ('brand_name', models.CharField(max_length=30)),
                ('model_name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=10000)),
                ('internal_rim_width', models.CharField(max_length=10)),
                ('external_rim_width', models.CharField(max_length=10)),
                ('spokecount', models.IntegerField()),
                ('spoke_materaial', models.CharField(max_length=20)),
                ('rimdepth', models.CharField(max_length=10)),
                ('axlesizeF', models.CharField(max_length=10)),
                ('axlesizeR', models.CharField(max_length=10)),
                ('weight_grams', models.IntegerField()),
                ('brake_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='bikes',
            old_name='content',
            new_name='description',
        ),
    ]
