# Generated by Django 5.0.4 on 2024-05-16 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0002_tyre_wheel_rename_content_bikes_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikes',
            name='wheels',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bikes.wheel'),
        ),
    ]
