# Generated by Django 5.0.4 on 2024-05-16 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0003_bikes_wheels'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikes',
            name='Tyre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bikes.tyre'),
        ),
    ]
