# Generated by Django 5.0.4 on 2024-05-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0004_bikes_tyre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='media')),
                ('model_name', models.CharField(max_length=255)),
                ('rotor_size', models.CharField(choices=[('140', '140mm'), ('160', '160mm'), ('160/140', '160mm / 140mm'), ('180', '180mm'), ('200', '200mm')], max_length=255)),
            ],
        ),
    ]
