# Generated by Django 5.0.4 on 2024-05-16 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0005_groupset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='media')),
                ('model_name', models.CharField(max_length=255)),
                ('links_count', models.BigIntegerField()),
                ('brand_name', models.CharField(max_length=255)),
                ('colour', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='bikes',
            name='Groupset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bikes.groupset'),
        ),
        migrations.AddField(
            model_name='groupset',
            name='Crankset',
            field=models.CharField(choices=[('50/34', 'compact'), ('52/36', 'semi-compact'), ('non-standard', 'other')], default='not set', max_length=255),
        ),
        migrations.AddField(
            model_name='groupset',
            name='other',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='groupset',
            name='Chain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bikes.chain'),
        ),
    ]
