# Generated by Django 5.0.4 on 2024-05-16 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0006_chain_bikes_groupset_groupset_crankset_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wheel',
            old_name='spoke_materaial',
            new_name='spoke_material',
        ),
    ]
