# Generated by Django 5.0.4 on 2024-05-16 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0007_rename_spoke_materaial_wheel_spoke_material'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupset',
            old_name='Crankset',
            new_name='crankset',
        ),
    ]
