# Generated by Django 5.0.4 on 2024-05-16 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0008_rename_crankset_groupset_crankset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupset',
            old_name='Chain',
            new_name='chain',
        ),
    ]
