# Generated by Django 5.0.4 on 2024-05-16 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0009_rename_chain_groupset_chain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bikes',
            old_name='Groupset',
            new_name='groupset',
        ),
        migrations.RenameField(
            model_name='bikes',
            old_name='Tyre',
            new_name='tyre',
        ),
    ]
