# Generated by Django 5.0.4 on 2024-05-16 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0010_rename_groupset_bikes_groupset_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bikes',
            new_name='Bike',
        ),
    ]
