# Generated by Django 5.0.4 on 2024-05-23 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0011_rename_bikes_bike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bike',
            old_name='modelname',
            new_name='model_name',
        ),
    ]
