# Generated by Django 5.0.4 on 2024-05-30 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0012_rename_modelname_bike_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='groupset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupset', to='bikes.groupset'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='tyre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tyre', to='bikes.tyre'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='wheels',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wheels', to='bikes.wheel'),
        ),
    ]
