# Generated by Django 5.0.4 on 2024-06-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Us', max_length=200)),
                ('welcome_message', models.TextField()),
                ('who_we_are', models.TextField()),
                ('what_we_do', models.TextField()),
                ('why_choose_us', models.TextField()),
                ('footer_message', models.CharField(default='&copy; 2024 RobbieFall Cycles. All rights reserved.', max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Aboutuspage',
        ),
    ]
