# Generated by Django 5.0.4 on 2024-06-20 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_aboutus_delete_aboutuspage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='footer_message',
        ),
    ]
