# Generated by Django 5.0.4 on 2024-06-20 12:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_aboutus_footer_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='welcome_message',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='what_we_do',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='who_we_are',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='why_choose_us',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
