# Generated by Django 5.0.4 on 2024-06-20 13:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_aboutus_welcome_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='data',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
